### PR TITLE
Closes #244 #251 reduces cyclomatic complexity and cleanup of `.lintr`

### LINKED ISSUE #244: Reduce cyclomatic complexity
## Background

While working on `xportr_length()` the cyclomatic complexity lintr was failing.

What should I do to resolve this lint error? image

It has to do with the number of conditions being used in a function.  https://en.wikipedia.org/wiki/Cyclomatic_complexity

I increased it to 18 in the `.lintr` file so this would check.  Will make an issue for someone to look into for next release.

_Originally posted by @bms63 in https://github.com/atorus-research/xportr/issues/238#issuecomment-1954306342_

## Definition of Done

- [ ] Reduce the cyclomatic complexity of `xportr_length()`
- [ ] Reduce `.lintr` file back to default of 15

### PR DESCRIPTION
**Pull request by averissimo**
### Changes Description

- Reduces complexity of `xportr_length` and `xportr_format` to below linter default threshold
- Reinstates linter rules:
  - `object_name_linter`: `snake_case` with exception of `_xportr.attr_name_` attributes and ADaM uppercase variables (`ADSL`).

### Task List

- [x] The spirit of xportr is met in your Pull Request
- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Summary of changes filled out in the above Changes Description. Can be removed or left blank if changes are minor/self-explanatory.
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Use `styler` package and functions to style files accordingly.
- [x] New functions or arguments follow established convention found in the [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers).
- [x] Updated relevant unit tests or have written new unit tests. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Unit-Tests) for conventions used in this package.
- [x] Creation/updated relevant roxygen headers and examples. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers) for conventions used in this package.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Run `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new/updated functions occur on the "Reference" page.
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] The `NEWS.md` entry should go under the `# xportr development version` section. Don't worry about updating the version because it will be auto-updated using the `vbump.yaml` CI.
- [x] Address any updates needed for vignettes and/or templates.
- [x] Link the issue Development Panel so that it closes after successful merging.
- [x] The developer is responsible for fixing merge conflicts not the Reviewer.
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

File: R/length.R [hunk 1]
```diff
@@ -121,35 +121,27 @@ xportr_length <- function(.df,
...
-
-
+    # Build `width` attribute
+    vapply(
+      names(.df),
+      function(i) {
+        if (i %in% miss_vars || is.na(length_metadata[[i]])) {
+          as.numeric(length_data[[i]])
+        } else {
+          as.numeric(length_metadata[[i]])
```
Comment (averissimo) [inline R/length.R:139]: @sophie-gem can you confirm that this can be safely coerced to numeric?

Thanks!

(avoids a `for` loop that adds complexity)

File: R/type.R [hunk 2]
```diff
@@ -104,10 +104,10 @@ xportr_type <- function(.df,
   domain_name <- getOption("xportr.domain_name")
   variable_name <- getOption("xportr.variable_name")
   type_name <- getOption("xportr.type_name")
-  characterTypes <- c(getOption("xportr.character_types"), "_character")
-  characterMetadataTypes <- c(getOption("xportr.character_metadata_types"), "_character")
-  numericMetadataTypes <- c(getOption("xportr.numeric_metadata_types"), "_numeric")
-  numericTypes <- c(getOption("xportr.numeric_types"), "_numeric")
+  character_types <- c(getOption("xportr.character_types"), "_character")
```
Comment (averissimo) [inline R/type.R:107]: Complying with changes to `.lintr` file (using snake_case)

File: R/length.R [hunk 3]
```diff
@@ -160,7 +152,17 @@ xportr_length <- function(.df,
...
+    # Build `width` attribute
+    length_data[names(.df)]
+  }
+
+  for (i in names(.df)) {
+    attr(.df[[i]], "width") <- width_attr[[i]]
   }
 
+  # Message for missing var and missing length
+  length_log(miss_vars, miss_length, verbose)
```
Comment (averissimo) [inline R/length.R:165]: This can safely be moved as "else" condition doesn't change any of these variables)

File: R/length.R (hunk 1 above)
Comment (sophie-gem) [reply R/length.R:139]: Hi @averissimo, I didn't work on the `length.R` script - I think it may have been @cpiraux - can you help here?

Comment (cpiraux) [reply R/length.R:139]: I confirm it can be coerced to numeric

**Review by cpiraux — APPROVED** [review]
Thank you for implementing this! I've reviewed the changes made to format.R and length.R, and everything looks good to me

**Review by bms63 — APPROVED** [review]
Thank you @averissimo for helping clean up our code!!  Looks very nice!
